[package]
name = "dawnstore-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = {version = "4.5.54", features = ["derive"]}
color-eyre.workspace = true
reqwest = { version = "0.13", features = ["json"] }
