[package]
name = "dawnstore-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = {version = "4.5.54", features = ["derive", "env"]}
serde.workspace = true
serde_yml = "0.0.12"
color-eyre.workspace = true
tokio.workspace = true
dawnstore-client-lib = { path = "../dawnstore-client-lib" }
