[package]
name = "dawnstore-client-lib"
version = "0.1.0"
edition = "2024"

[dependencies]
serde_json.workspace = true
reqwest = { version = "0.13", features = ["json"] }
thiserror.workspace = true
serde.workspace = true
dawnstore-lib = { path = "../dawnstore-lib" }
