[package]
name = "dawnstore-lib"
version = "0.1.0"
edition = "2024"

[dependencies]
serde.workspace = true
chrono.workspace = true
uuid.workspace = true
serde_json.workspace = true
schemars.workspace = true
